development:
  adapter: postgresql
  encoding: utf8
  database: customers_app_development
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: customers_app_test
  pool: 5